name: backdoor_2
attacks:
    gan:
        seeds: [0, 1, 2]
        test_without_backdoor: True
        datasets: [mnist, omniglot]
        backdoor:
            proportion: 0.5
        gan:
            generator: UResNet
            discriminator: DenseNet
            batch_sizes: [256, 128]
            train_ratio: 5
            lr: 1.e-4
            max_epochs: 30
            num_gpus: 4
            num_workers: 16
        classifier:
            models: [MNISTCNN, MNISTCNN]
            aug_transforms:
                mnist:
                    train: mnist_train
                    test: mnist_test
                cifar10:
                    train: mnist_train
                    test: mnist_test
            batch_sizes: [1024, 1024]
            lrs: [1.e-3, 1.e-3]
            max_epochs: 300
            num_gpus: 4
            num_workers: 16